GET http://127.0.0.1:8000/api/users/
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba

###
GET http://127.0.0.1:8000/api/users/?limit=2
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba




###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "66848797leoq@mail.ru",
  "username": "66879487leoq",
  "first_name": "Leo",
  "last_name": "Pug",
  "password": "userQW12!"
}
###
GET http://127.0.0.1:8000/api/users/2/
Authorization: Token b3aba692a330a8e32b94c5cfd1a4edc3a2ed1126

###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 370bec858776287753ac8e3117d3b33d44d6872a


###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token 412942be3b818b5e76a8aaed69ba4bd4c7948da5
Content-Type: application/json

{
  "current_password": "userQW12!",
  "new_password": "use266612!"
}



###
GET http://127.0.0.1:8000/api/users/subscriptions/
###
GET http://127.0.0.1:8000/api/users/3/subscribe/



###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "leo@mail.ru",
  "password": "userQW12!"
}

###
POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token 309a5a8189d51130ca45d736cb6bc2361c4083a5

















###
GET http://127.0.0.1:8000/api/recipes/?limit=2&page=4
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba

###
GET http://127.0.0.1:8000/api/recipes/



















###
GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/tags/1/










###
GET http://127.0.0.1:8000/api/ingredients/?name=лим

###
GET http://127.0.0.1:8000/api/ingredients/?search=виш
###
GET http://127.0.0.1:8000/api/ingredients/1/











###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba

###
GET http://127.0.0.1:8000/api/recipes/?author=admin
Authorization: Token a04b6ec3a3cb425a06ff24e29b230cf6637eef76


###
GET http://127.0.0.1:8000/api/recipes/?tags=dinner
Authorization: Token a04b6ec3a3cb425a06ff24e29b230cf6637eef76




##############
###
GET http://127.0.0.1:8000/api/recipes/?author=admin
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba



###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=false
Authorization: Token a04b6ec3a3cb425a06ff24e29b230cf6637eef76


###
GET http://127.0.0.1:8000/api/recipes/2/
Authorization: Token 370bec858776287753ac8e3117d3b33d44d6872a




###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba
Content-Type: application/json

{
  "ingredients": [
    {
      "id": 100,
      "amount": 15
    },
    {
      "id": 200,
      "amount": 15
    },
    {
      "id": 300,
      "amount": 15
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "image1",
  "name": "one",
  "text": "1",
  "cooking_time": 30
}




















###
GET http://127.0.0.1:8000/api/recipes/17/
Authorization: Token 370bec858776287753ac8e3117d3b33d44d6872a



###
PATCH http://127.0.0.1:8000/api/recipes/29/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913
Content-Type: application/json

{
  "ingredients": [
    {
      "id": 100,
      "amount": 15
    },
    {
      "id": 200,
      "amount": 15
    },
        {
      "id": 300,
      "amount": 15
    }
  ],
  "tags": [
    3,
    1
  ],
  "image": "im1",
  "name": "one",
  "text": "1",
  "cooking_time": 3
}



###
DELETE http://127.0.0.1:8000/api/recipes/29/
Authorization: Token 370bec858776287753ac8e3117d3b33d44d6872a







###
GET http://127.0.0.1:8000/api/recipes/2/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913






###
POST http://127.0.0.1:8000/api/recipes/10/favorite/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913


###
DELETE http://127.0.0.1:8000/api/recipes/10/favorite/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913






###
POST http://127.0.0.1:8000/api/recipes/10/shopping_cart/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913


###
DELETE http://127.0.0.1:8000/api/recipes/10/shopping_cart/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913



###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token 2e587d05b90e5f9fab5ecb47726aa4d559593913

















###
POST http://127.0.0.1:8000/api/users/1/subscribe/?recipes_limit=2
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba


###
DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba


###
GET http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token 263e6a99bdf9eed9438adda0004a0127333e55ba


