GET http://127.0.0.1:8000/api/users/


###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "as@mail.ru",
  "username": "as",
  "first_name": "as",
  "last_name": "as",
  "password": "userQW12!"
}
###
GET http://127.0.0.1:8000/api/users/5/
Authorization: Token d13f9e94c682f25f0275c6402d82ac57a2d72ae6

###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 412942be3b818b5e76a8aaed69ba4bd4c7948da5

###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token 412942be3b818b5e76a8aaed69ba4bd4c7948da5
Content-Type: application/json

{
  "current_password": "userQW12!",
  "new_password": "use266612!"
}



###
GET http://127.0.0.1:8000/api/users/subscriptions/
###
GET http://127.0.0.1:8000/api/users/3/subscribe/

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "art23@mail.ru",
  "password": "art23"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "userQW12!"
}

###
POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token 309a5a8189d51130ca45d736cb6bc2361c4083a5


GET http://127.0.0.1:8000/api/recipes/

###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json

{
  "ingredients": [
    2
  ],
  "tags": [
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1,
  "author": 1
}


###
GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/tags/1/
###
GET http://127.0.0.1:8000/api/ingredients/
###
GET http://127.0.0.1:8000/api/ingredients/1/




###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89

###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=True
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89

###
GET http://127.0.0.1:8000/api/recipes/?author=admin
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89

###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89



###
GET http://127.0.0.1:8000/api/recipes/9/
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89




###
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token 816b625f0400602a33f90883f35d65c9ba078a89
Content-Type: application/json

{
  "ingredients": [
    {
      "id": 2,
      "amount": 22
    }
  ],
  "tags": [
    2,
    1
  ],
  "image": "77i55m4age",
  "name": "007ge",
  "text": "a5g5e4",
  "cooking_time": 99
}











###
{
  "ingredients": [
    {
      "name": "55",
      "measurement_unit": "155"
    }
  ],
  "tags": [
    {
      "id": 2,
      "name": "2Полдник",
      "slug": "2pol",
      "color": "#FBCEB1"
    }
  ],
  "image": "CByxOy",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}


###
